name: technician_app
description: "Image Mobiles Technician Live Tracking & Field Job Management Mobile Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.0
  http: ^1.2.1
  firebase_core: ^4.14.0
  firebase_auth: ^6.6.1
  cloud_firestore: ^6.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
