// File generated by FlutterFire CLI & configured for Image Mobiles.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2s74W9EaGO-Zs21iDU0f0clajykfPrVw',
    appId: '1:934286397615:web:41f66d768310816bc0445a',
    messagingSenderId: '934286397615',
    projectId: 'imagemobiles-45aeb',
    authDomain: 'imagemobiles-45aeb.firebaseapp.com',
    storageBucket: 'imagemobiles-45aeb.firebasestorage.app',
    measurementId: 'G-9BG1PG35G7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2BI5ho-bb1rTWBbsolIgh0iEogrxGJaY',
    appId: '1:934286397615:android:66fbfda7168a3274c0445a',
    messagingSenderId: '934286397615',
    projectId: 'imagemobiles-45aeb',
    storageBucket: 'imagemobiles-45aeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2BI5ho-bb1rTWBbsolIgh0iEogrxGJaY',
    appId: '1:934286397615:ios:66fbfda7168a3274c0445a',
    messagingSenderId: '934286397615',
    projectId: 'imagemobiles-45aeb',
    storageBucket: 'imagemobiles-45aeb.firebasestorage.app',
    androidClientId: '934286397615-android.apps.googleusercontent.com',
    iosBundleId: 'in.imagemobiles.technicianApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2BI5ho-bb1rTWBbsolIgh0iEogrxGJaY',
    appId: '1:934286397615:ios:66fbfda7168a3274c0445a',
    messagingSenderId: '934286397615',
    projectId: 'imagemobiles-45aeb',
    storageBucket: 'imagemobiles-45aeb.firebasestorage.app',
    iosBundleId: 'in.imagemobiles.technicianApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2s74W9EaGO-Zs21iDU0f0clajykfPrVw',
    appId: '1:934286397615:web:41f66d768310816bc0445a',
    messagingSenderId: '934286397615',
    projectId: 'imagemobiles-45aeb',
    authDomain: 'imagemobiles-45aeb.firebaseapp.com',
    storageBucket: 'imagemobiles-45aeb.firebasestorage.app',
  );
}
